CREATE TABLE IF NOT EXISTS users (id TEXT PRIMARY KEY, role TEXT NOT NULL, name TEXT NOT NULL, class_id TEXT, login TEXT UNIQUE NOT NULL, salt TEXT NOT NULL, hash TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS classes (id TEXT PRIMARY KEY, teacher_id TEXT NOT NULL, name TEXT NOT NULL, code TEXT UNIQUE NOT NULL, grade INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS sessions (token TEXT PRIMARY KEY, user_id TEXT NOT NULL, expires INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS attempts (id TEXT PRIMARY KEY, student_id TEXT NOT NULL, form TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'open', answers TEXT, result TEXT, created TEXT NOT NULL, submitted TEXT);
CREATE UNIQUE INDEX IF NOT EXISTS one_open_attempt ON attempts(student_id) WHERE status='open';
CREATE TABLE IF NOT EXISTS plans (student_id TEXT PRIMARY KEY, book_id TEXT NOT NULL, variant TEXT NOT NULL, goal TEXT NOT NULL, teacher_id TEXT NOT NULL, reviewed INTEGER NOT NULL, updated TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS entries (id TEXT PRIMARY KEY, student_id TEXT NOT NULL, book_id TEXT NOT NULL, payload TEXT NOT NULL, created TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS feedback (entry_id TEXT PRIMARY KEY, teacher_id TEXT NOT NULL, message TEXT NOT NULL, updated TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS limits (key TEXT PRIMARY KEY, count INTEGER NOT NULL, reset INTEGER NOT NULL);

CREATE TABLE IF NOT EXISTS assessment_forms (id TEXT PRIMARY KEY, bank TEXT NOT NULL);
